name = "d1-template"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "d1-template-database"
database_id = "884f3696-6e16-4e78-b5f7-d2434addf4d0"

[vars]
JWT_SECRET = "your-jwt-secret-change-this"
WORKER_URL = "d1-template.gabrielogbeks.workers.dev"
